### ISSUE TITLE
not able run this model in docker

### ISSUE THREAD

**Issue by tiru1930** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#32]
```
Traceback (most recent call last):
  File "kfserving-absa.py", line 30, in <module>
    model.load()
  File "kfserving-absa.py", line 14, in load
    self.nlp = absa.load()
  File "/usr/local/lib/python3.7/site-packages/aspect_based_sentiment_analysis/loads.py", line 34, in load
    model = BertABSClassifier.from_pretrained(name, config=config)
  File "/usr/local/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 730, in from_pretrained
    model(model.dummy_inputs, training=False)  # build the network with dummy inputs
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aspect_based_sentiment_analysis/models.py", line 150, in call
    logits = self.classifier(pooled_output)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 964, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2398, in _maybe_build
    self.input_spec, inputs, self.name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py", line 196, in assert_input_compatibility
    str(x.shape.as_list()))
ValueError: Input 0 of layer classifier is incompatible with the layer: : expected min_ndim=2, found ndim=0. Full shape received: []
```
aspect-based-sentiment-analysis==2.0.1
tensorflow==2.2.0

tried different tf version but issue same

**Comment by jedmijares** [comment]
I'm having the same problem outside of Docker.

**Comment by rolczynski** [comment]
Please update to the version `2.0.2` - it should work now 😊
