### ISSUE TITLE
Getting error with basic first code

### ISSUE THREAD

**Issue by theoflaus** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#70]
Hi, I tried only the first lines of code that were : 
```
import aspect_based_sentiment_analysis as absa

nlp = absa.load()
text = ("We are great fans of Slack, but we wish the subscriptions "
        "were more accessible to small startups.")

slack, price = nlp(text, aspects=['slack', 'price'])
assert price.sentiment == absa.Sentiment.negative
assert slack.sentiment == absa.Sentiment.positive
```

and got the following error : 

Traceback (most recent call last):
  File "test_absa.py", line 3, in <module>
    nlp = absa.load()
  File "C:\Users\theo.flaus\Anaconda3\envs\test\lib\site-packages\aspect_based_sentiment_analysis\loads.py", line 34, in load
    model = BertABSClassifier.from_pretrained(name, config=config)
  File "C:\Users\theo.flaus\Anaconda3\envs\test\lib\site-packages\transformers\modeling_tf_utils.py", line 2699, in from_pretrained
    model(model.dummy_inputs)  # build the network with dummy inputs
  File "C:\Users\theo.flaus\Anaconda3\envs\test\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\theo.flaus\Anaconda3\envs\test\lib\site-packages\aspect_based_sentiment_analysis\models.py", line 141, in call
    outputs = self.bert(
ValueError: Exception encountered when calling layer "bert_abs_classifier" (type BertABSClassifier).
The first argument to `Layer.call` must always be passed.

Call arguments received by layer "bert_abs_classifier" (type BertABSClassifier):
  • token_ids={'input_ids': 'tf.Tensor(shape=(3, 5), dtype=int32)'}
  • attention_mask=None
  • token_type_ids=None
  • training=False
  • bert_kwargs=<class 'inspect._empty'>

Any idea how to solve this ?

**Comment by klawicka** [comment]
Same here, any solutions?

**Comment by octokami** [comment]
I got the same error.  For me it was solved when I installed from the environment.yml. My problem in specific is that I had Python >3.7

**Comment by VedantNemane** [comment]
A bit late, but can confirm (at least for me) changing Python version immediately fixed the issue. 

To create a new virtual environment with Python version 3.6 in Jupyter Notebook, take a look at [this](https://janakiev.com/blog/jupyter-virtual-envs/#:~:text=To%20delete%20the%20virtual%20environment,virtualenv%20documentation%20or%20venv%20documentation ).  

This is what it looks like for me: 
![image](https://user-images.githubusercontent.com/63410656/228256269-de2bf011-6492-4559-afe0-4e4853f96d95.png)

**Comment by sudip-modi** [comment]
I am unable to install python version 3.6 on jupyter notebook colab. I get an error like this
![image](https://github.com/ScalaConsultants/Aspect-Based-Sentiment-Analysis/assets/64591309/896e6e16-2f5f-4cdd-b154-00e431a0ca82)
Any ideas why this might be the case?
@VedantNemane

**Comment by morinstar** [comment]
@VedantNemane I installed 3.6.13 venv on pycharm and that can deal with the installation at least. btw 3.6.8 and 3.6.10 didn't help installing this package. Thanks for the guide!

**Comment by gyanendrarawat** [comment]
for me error is :
RecursionError: maximum recursion depth exceeded in instancecheck
